### ISSUE TITLE
What is JOBFILE?

### ISSUE THREAD

**Issue by nojhan** [SebKuzminsky/svg2gcode#2]
Documentation does not explain what is the needed JOBFILE argument to the command line.
Seems to except a JSON, but no default version is provided to play with the software.

**Comment by SebKuzminsky** [comment]
The jobfile format is described in the documentation/manpage: https://github.com/SebKuzminsky/svg2gcode/blob/master/svg2gcode.adoc#job-file-format

There are also many jobfile examples included in the test suite, for example: https://github.com/SebKuzminsky/svg2gcode/blob/master/test/svg2gcode/5-shapes/pocket-2/test.s2g
