### ISSUE TITLE
Tests failing for missing `flatten_all_paths`

### ISSUE THREAD

**Issue by nojhan** [SebKuzminsky/svg2gcode#3]
As of version e43d755, on Ubuntu 20.04 focal, without having installed linuxcnc-uspace (given that the key server return an error).

Running `runtest` from `test` returns the same error for all tests:
```
AttributeError: 'Document' object has no attribute 'flatten_all_paths'
```

**Comment by asadafasab** [comment]
On fedora 37 (without linuxcnc-uspace) I have error:

```
Traceback (most recent call last):
  File "../svg2gcode/svg2gcode", line 1128, in <module>
    svg = gcoder.svg(args.SVG, gcode_origin)
  File "../svg2gcode/gcoder.py", line 184, in __init__
    self.results = self.doc.flatten_all_paths()
AttributeError: 'Document' object has no attribute 'flatten_all_paths'
```


This fix works for me:

```python
# gcoder.py
self.doc = svgpathtools.Document(self.svg_file)
#self.results = self.doc.flatten_all_paths()
self.paths = self.doc.paths()
```

**Comment by SebKuzminsky** [comment]
`flatten_all_paths` is a new feature of svgpathtools.  This error sounds like your svgpathtools submodule is out of date.  Run `git submodule update` to update it.
