### ISSUE TITLE
Update svgpathtools

### ISSUE THREAD

**Issue by nojhan** [SebKuzminsky/svg2gcode#4]
The current svgpathtools submodule is incompatible with python > 3.10, since collections' classes needs to be imported from collections.abc. mathandy's repository is fixed.

**Comment by SebKuzminsky** [comment]
Thanks for the heads up.

I have pushed a branch called `update-submodule` that updates svg2gcode to use the latest master branch in mathandy's svgpathtools.

This unfortunately that has a bug, mathandy/svgpathtools#200, so there may be some breakage depending on your input svg files.  I will wait for that bug to be fixed before merging the `update-submodule` branch here.

**Comment by SebKuzminsky** [comment]
Ok, this should be fixed now, please try and let me know here if this is working for you.

The svgpathtools submodule of svg2gcode still points to my repo, to a commit that's the current master in mathandy/svgpathtools, plus a fix for the arc sweep issue.
